### ISSUE TITLE
Possible Issues with withAsyncComponent

### ISSUE THREAD

**Issue by kikoanis** [ctrlplusb/react-async-component#12]
Thanks for putting this together.

[Line 64](https://github.com/ctrlplusb/react-async-component/blob/master/src/withAsyncComponents.js#L64)
```
 if (rehydrateState) {
          if (!rehydrateState.resolved[id]) {
            return false;
          }
....
```
Not sure what rehydrateState.resolved[id] is referring to, but in the case of rehydrateState.resolved not defined it throws an error which I guess you should guard against its null-ability.

[Line 103](https://github.com/ctrlplusb/react-async-component/blob/master/src/withAsyncComponents.js#L103)
```
 state: { resolved: execContext.getResolved() },
```
I think you kill state rehydration too soon before it gets to the client.
Currently to get around this I only requery store.getState() which is not ideal.

**Comment by ctrlplusb** [comment]
Thanks for the report @kikoanis 

I'll review these and make sure the cases are covered in the next batch of tests I plan to write.

**Comment by ctrlplusb** [comment]
Hi @kikoanis!

I am reviewing your issue.  A couple of questions...

> Not sure what rehydrateState.resolved[id] is referring to, but in the case of rehydrateState.resolved not defined it throws an error which I guess you should guard against its null-ability.

Have you experienced an undefined error?

> I think you kill state rehydration too soon before it gets to the client.
> Currently to get around this I only requery store.getState() which is not ideal.

I am a bit confused on this one.  I believe `store.getState()` is against the redux store, if so this should not be affected by the line you have highlighted. The line in question is to remove the state that is used by this library when rehydrating a client with the async components that were resolved in a server render.  This data is only needed once, and we therefore destroy to avoid issues with hot reloading and/or remounting cases.

**Comment by kikoanis** [comment]
> Have you experienced an undefined error?

This is the error message I am getting

![image](https://cloud.githubusercontent.com/assets/615849/22866363/f68ac202-f13a-11e6-9207-821af3a5347c.png)

Which I tracked it down to line 84 in the compiled file
![image](https://cloud.githubusercontent.com/assets/615849/22866386/5963b4f6-f13b-11e6-8781-f0d3e7a934f8.png)

> I am a bit confused on this one. I believe store.getState() is against the redux store
Yes it is.

>  This data is only needed once, and we therefore destroy to avoid issues with hot reloading and/or remounting cases.

I know this is for the client to use the server state only the first time. But the problem is that the client is not getting it first time. Not sure if we need the client to destroy it rather than the server, may be by replacing this line

```
state: { resolved: execContext.getResolved() },
```
by this
```
state: typeof window !== 'undefined' ? { resolved: execContext.getResolved() } : rehydrateState,
```

**Comment by ctrlplusb** [comment]
Hmm, something definitely sounds off here.  It appears the state is not being configured properly for your environment.  Is there any chance you could share your configuration with me so that I can review?

**Comment by kikoanis** [comment]
Thanks for getting back on it.
Will try to upload something for you to review based on your redux branch. Will keep you informed

**Comment by kikoanis** [comment]
doh... this will take sometime as the redux branch is way behind and the project I am working on is private one and I am afraid I am not in a position to share it.

Anyway. On the server side what I am getting as a state is only this 
```
{ 
   resolved: { 
      '1': true
   }
}
```
There is no elements of the other store state which is why I am doing Store.getState() again on the client side. Obviously this defeats the whole idea of SSR, doesn't it?

You may be right about the possibility of mis-configuration on our side so I will try to update the redux-opinionated branch to get a solid example to debug and review.

**Comment by kikoanis** [comment]
OK... So I think I managed to resolve the issue for now by adding a new reducer entry for "resolved" as an empty object into the redux store. The "resolved" entry is mentioned in the withAsyncComponent. 
Still not sure if the "resolved" entry is for tracking changes between server and client internally, why we still need it in the redux store. 

Unless I am missing something else not obvious in your react-universally@next
