### ISSUE TITLE
How to write tests?

### ISSUE THREAD

**Issue by andreyluiz** [ctrlplusb/react-async-component#16]
I have a container that loads a component async with react-async-component and then perform the connection with redux's state.

It works nicely, however, I could not find a way to test it. The component (obviously) is not ready when the tests runs. In this case enzyme finds an empty react component.

Code examples:

**ForgotPage.js**
```javascript
// @flow
import { createAsyncComponent } from 'react-async-component';
import { connect } from 'react-redux';
import requestPasswordRecovery from '../../shared/state/actions/passwordRecovery';

const Forgot = createAsyncComponent({
  resolve: () => new Promise(resolve =>
    // $FlowFixMe
    require.ensure([], (require) => {
      resolve(require('../components/Forgot'));
    }, 'forgot'),
  ),
  ssrMode: 'boundary',
});

const mapStateToProps = state => ({
  passwordRecovery: state.passwordRecovery,
});

const mapDispatchToProps = dispatch => ({
  requestPasswordRecovery: data => dispatch(requestPasswordRecovery(data)),
});

export default connect(mapStateToProps, mapDispatchToProps)(Forgot);
```

This code does not work with my integration tests. If, instead of loading it async I just import it, tests run fine.

Is there a way to get this working with tests?

**Comment by cescoferraro** [comment]
@andreyluiz why dont you use `require('../components/Forgot')` in your tests instead of `Forgot`. So you wont have this problem in your test env?

**Comment by neenhouse** [comment]
This doesn't always work.  If you want to test integration of async components within a container, you need to be able to mock the async loading of them.  We need better documentation here on how you do that.   Simply flipping to sync require isn't really properly testing that scenario.

**Comment by flasd** [comment]
Managed to test by using the same server side rendering logic and [cheerio](https://github.com/cheeriojs/cheerio) to parse the output.
```javascript
import React from 'react';
import asyncBootstrapper from 'react-async-bootstrapper';
import cheerio from 'cheerio';
import { AsyncComponentProvider, createAsyncContext } from 'react-async-component';
import { expect } from 'chai';
import { renderToStaticMarkup } from 'react-dom/server';

import Container from './index';

describe('Some Container', () => {
    it('should resolve on the server', (done) => {
        const asyncContext = createAsyncContext();

        const component = (
            <AsyncComponentProvider asyncContext={asyncContext}>
                <Container />
            </AsyncComponentProvider>
        );

        asyncBootstrapper(component)
            .then(() => {
                const html = renderToStaticMarkup(component);
                const $ = cheerio.load(html);

                expect($('div').children().length).to.equal(2);
                // etc...

                done();
            })
            .catch(error => {
                done(error);
            });
    });
});
```

**Comment by ctrlplusb** [comment]
Kent C Dodds also has an integration test friendly library [`react-testing-library`](https://github.com/kentcdodds/react-testing-library). I would recommend looking at that one too 👍
