### ISSUE TITLE
Update docs to reflect that React Hot Loader is not supported

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-async-component#17]
It is unfortunately too flaky to use this library with RHL.

I recommend using webpack's standard hot module reloading instead.

**Comment by plhosk** [comment]
Perhaps there could be an example showing the best way to have this enabled in Prod while RHL is enabled only in Dev.

**Comment by gabeweaver** [comment]
@plhosk I've only been using this async component library for a day, but I haven't had any issues with RHL with this option in my main entry:
```
if (module.hot) {
  module.hot.accept('./Root', () => {
    const NextRoot = require('./Root').default
    const hotApp = (
      <AppContainer>
        <NextRoot store={store} />
      </AppContainer>
    )

    withAsyncComponents(hotApp)
      .then((result) => {
        const { appWithAsyncComponents } = result
        return render(appWithAsyncComponents, MOUNT_NODE)
      })
      .catch(err => logger.log.error('Error bootstrapping the application', err))
  })
}
```

this is assuming you're on webpack 2 and RHL 3 (and they're configured correctly)

**Comment by gabeweaver** [comment]
Scratch that...running into issues now ;(

**Comment by ctrlplusb** [comment]
I do have some new ideas, after implemented we could retry RHL.

**Comment by ctrlplusb** [comment]
Closing this as I have made some progress on RHL support. Track in #14
