### ISSUE TITLE
Investigate possible solutions to React Hot Loader compatability

### ISSUE THREAD

**Issue by dlebedynskyi** [ctrlplusb/react-async-component#2]
Simplification looks really nice. What would be  great is to add old `disable` flag from code-split.  
This will help to switch between hot reload or async-component in runtime/build. 
Something like 
```jsx
// client-entry.js 

import { withAsyncComponents } from 'react-async-component'; // 👈

const app = <MyApp />;

//       adding disabled based on hot reload env var  👇
const render = (app) => withAsyncComponents(app, process.env.HOT_RELOAD)
.then((result) => {
    const {
      appWithAsyncComponents: Root
    } = result;
   ReactDOM.render(
      <ReactHotLoader>
        <Provider store={store}>
              <Router><Root/></Router>
        </Provider>
      </ReactHotLoader>,
      document.getElementById('app'));
  });

// Hot reloading on the client
if (process.env.NODE_ENV === 'development' && module.hot) {
  module.hot.accept('./app/routing/Root', () => {
    const Root = require('./app/routing/Root').default; // eslint-disable-line no-shadow

    render(Root);
  });
}

const Root = require('./app/routing/Root').default; // eslint-disable-line no-shadow
render(Root);

```

Similar on server side if needed
```jsx 
withAsyncComponents(app, process.env.HOT_RELOAD)
    //        👇 and you get back a result object.
    .then((result) => {
      const {
        // ❗️ The result includes a decorated version of your app
        // that will have the async components initialised for
        // the renderToString call.
        appWithAsyncComponents,
        // This state object represents the async components that
        // were rendered by the server. We will need to send
        // this back to the client, attaching it to the window
        // object so that the client can rehydrate the application
        // to the expected state and avoid React checksum issues.
        state,
        // This is the identifier you should use when attaching
        // the state to the "window" object.
        STATE_IDENTIFIER
      } = result;

      const appString = renderToString(appWithAsyncComponents);

```
What do you think? 
I can see great value if having ability to run hot reload for rapid dev of something during development (even if it not really working that great) and being able to switch to code split when needed - like production or debugging of something

**Comment by ctrlplusb** [comment]
Thanks for the suggestion @dlebedynskyi 

I am going to spend some time at some point doing a proper debug session that will hopefully shed some light on _if_ and _how_ we may achieve this.

**Comment by ctrlplusb** [comment]
🕺___REACT HOT LOADER WORKS___ 💃

No workarounds or plugins.  All pure React. :)

You just need to make sure you bind and export your components using my recommended pattern as described in the docs. :)

I am pushing all my latest experiments to the `next` branch of `react-universally`.

**Comment by ctrlplusb** [comment]
To be clear you don't need to change any code at all for it to work.  Use the async components as normal. Much nicer because you still get the async loading, so you can catch bugs with this, but get hot reloading on the result.

**Comment by dlebedynskyi** [comment]
@ctrlplusb 
Can you point me to 
> You just need to make sure you bind and export your components using my recommended pattern as described in the docs. :)
? being blind this morning

**Comment by ctrlplusb** [comment]
No worries.

https://github.com/ctrlplusb/react-async-component#browser-only-application

I describe the following folder structure for an AsyncComponent:

```
 |- AsyncProduct
    |- index.js
    |- Product.js
```

Read that full section.
