### ISSUE TITLE
Provide a synchronous version of "withAsyncComponents"

### ISSUE THREAD

**Issue by naltatis** [ctrlplusb/react-async-component#20]
I'm using `react-async-component` in a SSR context where all async components are `defer=true`. In this case there is no need to transfer state using `STATE_IDENTIFIER` from the server.

Wrapping the app in `withAsyncComponents` makes it harder to get working with data fetchers. We use `redial` and I'm quite happy with it.

I've been able to implement `react-async-component` synchronously by using `AsyncComponentProvider` directly.

```
import AsyncComponentProvider from 'react-async-component/commonjs/AsyncComponentProvider';
...
const app = (
  <AsyncComponentProvider execContext={createExecContext()}>
    <MyApp />
  </AsyncComponentProvider>
);
```

This uses internal API and I had to copy `createExecContext` into my project, but it works. I would like to have an official and simpler way of doing this.

**Comment by ctrlplusb** [comment]
Hey @naltatis 

I am making progress on this within the `next` branch.  Just to let you know. :)

**Comment by naltatis** [comment]
Sounds good, thanks for letting me know!

**Comment by ctrlplusb** [comment]
New alpha release supports just this. :)
