### ISSUE TITLE
Exception logging using Sentry.io

### ISSUE THREAD

**Issue by kennethtruong** [ctrlplusb/react-async-component#29]
Just wondering what do you recommend if I wanted to log exceptions using Sentry. The async components are catching the exception so I'm wondering is there a way to pass a handler to know when an error occurred. Or maybe are we able to get an option to not catch the exceptions?

**Comment by ctrlplusb** [comment]
Hi @kennethtruong 

You could add your own wrappers to your promises that first catch, log, then rethrow the errors.

```
asyncComponent(() => ({
  resolve: () => Promise.reject('💩')
    .catch((err) => { 
      logToSentry(err)
      throw err
   })
})
```

That's just an off the hand example, but you create a utility function to do the boilerplate for you.
