### ISSUE TITLE
Weird error when creating asyncComponent with router

### ISSUE THREAD

**Issue by justgook** [ctrlplusb/react-async-component#39]
```
Warning: Failed child context type: Cannot read property 'asyncComponentsAncestor' of undefined
    in AsyncComponent (created by Route)
    in Route
    in div
    in Router (created by ConnectedRouter)
    in ConnectedRouter
    in Provider
```
looks like there is no validation - that context could not exist - so it throws that error - but after that works as expected (from my point of view)

**Comment by justgook** [comment]
looks like related to the https://github.com/facebook/react/issues/3392

**Comment by Asp3ctus** [comment]
any workaround?

**Comment by ctrlplusb** [comment]
I have a fix for this in progress.

**Comment by ctrlplusb** [comment]
Fix is queued in master, should be released shortly.
