### ISSUE TITLE
In my Webstorm editor, show syntax errors, how to fix it

### ISSUE THREAD

**Issue by luojinghui** [ctrlplusb/react-async-component#46]
I have added before the reactjs grammar support, but you use this grammar is wrong, how to solve. Thank you.
![wechatimg1118](https://user-images.githubusercontent.com/12367406/27669589-197cf10a-5cba-11e7-9960-3571f9b39879.jpeg)

**Comment by codeBelt** [comment]
Do you have `React JSX` for you JavasScript language? I am no seeing what you are seeing in WebStorm.

![screenshot 2017-08-23 09 00 47](https://user-images.githubusercontent.com/2893563/29619884-df59deb8-87e1-11e7-83f4-6ae26cb9dc98.png)
