### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by bradennapier** [ctrlplusb/react-async-component#5]
I think you will need to do some extra error handling here.  This is a bug in my code I believe but react reports it as an error of AsyncComponent which will make debugging difficult:

```invariant.js:44 Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AsyncComponent`.```

**Comment by ctrlplusb** [comment]
Cool, any recommendations or thoughts around this?

**Comment by ctrlplusb** [comment]
There is now an error component for when a component resolution fails.
