### ISSUE TITLE
TypeScript & ES2015 Examples

### ISSUE THREAD

**Issue by codeBelt** [ctrlplusb/react-async-component#54]
First, this library is awesome!

Second, I want to show off my TypeScript and ES2015 examples using react-async-component. I also have react-hot-loader working with it. It took me a long time to get everything figured out so I hope it helps others.

Features are TypeScript or ES2015, Universal (SSR), React Hot Loader 3, React Router 4, Redux, Redux Saga, Redux Form, Async Component Code Splitting, Hapi, Webpack 3.

* [hapi-react-hot-loader-example](https://github.com/codeBelt/hapi-react-hot-loader-example) 
* [typescript-hapi-react-hot-loader-example](https://github.com/codeBelt/typescript-hapi-react-hot-loader-example)

**Comment by ctrlplusb** [comment]
Thanks dude!

I have published v1.0.0 on npm, which now bundles the typescript typings.

**Comment by bdoss** [comment]
@ctrlplusb I just saw this new release today, but the typings file doesn't seem to be included in the package that's pulled down from npm?

**Comment by ctrlplusb** [comment]
Argh, hmmm, I'll have to add it to the files array I think.  Shall post a new version up shortly.

**Comment by bdoss** [comment]
Yes, that's what it must be after poking around in the repo a little bit. :+1:

**Comment by ctrlplusb** [comment]
Done
