### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by AndreasPresthammer** [ctrlplusb/react-async-component#56]
I see that you already have an index.d.ts file in the project. Would be great if that was included in the npm package, or atleast made available under `@types/react-async-component`

**Comment by ctrlplusb** [comment]
Agreed, sorry, I am not a TS user so it escaped me. :)

Would you like to submit a PR?

**Comment by ctrlplusb** [comment]
It should be included with the latest package.

**Comment by AndreasPresthammer** [comment]
Thanks :)
