### ISSUE TITLE
React 16 Errors

### ISSUE THREAD

**Issue by bradennapier** [ctrlplusb/react-async-component#58]
Just tried an update to React 16 and it would appear an error with async component makes the app fail to load :(

```
warning.js:36 Warning: Failed child context type: Cannot read property 'asyncComponentsAncestor' of undefined
```

Says it is only a warning but my app no longer loads at all and this is the only error I can see..

**Comment by bkniffler** [comment]
I think you forgot to use AsyncProvider on your client bundle.

**Comment by bradennapier** [comment]
it says not to use that / it is pointless unless you are using SSR which I am not.

**Comment by bkniffler** [comment]
Did you try using it? When I forgot to add it (I'm using SSR) I had the same issue, after adding it, the issue was gone.

**Comment by ctrlplusb** [comment]
Damn that may be a bug then

**Comment by bradennapier** [comment]
Yeah it is just a warning... it is not actually breaking my app - something else was (having any module that forgets to set react as peer dependency will now pretty much break an app with no real reporting). 

I fixed this by adding the provider... it seems that react just adds that warning now if it sees any violation of context types. 

Not sure what to do in cases like this when the provider is actually optional...

**Comment by maxmantz** [comment]
Got the same warning and confirm that adding `AsyncComponentProvider` will fix it.

**Comment by codeBelt** [comment]
I am using React 16 and not seeing the issue on my repo [hapi-react-hot-loader-example](https://github.com/codeBelt/hapi-react-hot-loader-example). I am using `AsyncComponentProvider` on both my [client-side](https://github.com/codeBelt/hapi-react-hot-loader-example/blob/3974c9f88ec0a74d867e0a15d0547ce2ca20ee26/src/client.jsx#L31-L35) and [ssr](https://github.com/codeBelt/hapi-react-hot-loader-example/blob/3974c9f88ec0a74d867e0a15d0547ce2ca20ee26/src/server/controllers/ReactController.jsx#L25-L32) code.

**Comment by ctrlplusb** [comment]
FYI, I have a fix for the warning in progress. 👍

**Comment by ctrlplusb** [comment]
Fix is queued in master, should be released shortly.
