### ISSUE TITLE
Just to let you know it's pure magic!

### ISSUE THREAD

**Issue by JulienPradet** [ctrlplusb/react-async-component#6]
Hi :)

Sorry for the not so useful issue here but thanks a bunch for the lib!
I was starting to have a similar API myself but couldn't manage my way out.

If I can be of any help here, feel free to reach out. I'll be glad to give a hand!

**Comment by ctrlplusb** [comment]
It is always great to dilute the issues with some positive feedback! 😃 

So glad that you are finding it useful.  I am always super happy to bring on collaborators so if you would like to come on board and help me maintain this library I would welcome you with open arms. 😃
